vscode:
  extensions:
    - Equinusocio.vsc-community-material-theme@1.4.2:w1WjmCnuHbrOLEfj+UBKig==
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - HansUXdev.bootstrap5-snippets@1.2.4:a0VDfZWXIZ8kLhp9GNm4DA==